"use client";

import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/components/ui/card";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { buttonVariants } from "@/components/ui/button";
import { Button } from "@/components/ui/button";
import { useAppState } from "@/context/StateContext";

export default function SummaryCard() {
    const { activeCases, addActiveCase } = useAppState();

    // Get the last case in the list
    const lastCase =
        activeCases.length > 0 ? activeCases[activeCases.length - 1] : null;

    // Define the display values based on the last case
    const title = lastCase ? `Case #${lastCase.caseNumber}` : "No Active Cases";
    const description = lastCase
        ? lastCase.caseStatus
        : "Nothing requires your attention";
    const content = lastCase
        ? lastCase.caseDescription
        : "Ask me anything about the system, I am here to help you.";

    return (
        <div className="max-w-xl mx-auto mt-10">
            <Card>
                <CardHeader>
                    <CardTitle>{title}</CardTitle>
                    <CardDescription>{description}</CardDescription>
                </CardHeader>
                <CardContent className="text-sm text-muted-foreground/90 leading-normal prose">
                    <p className="mb-3">{content}</p>
                    <Button
                        className={cn(buttonVariants())}
                        onClick={() =>
                            addActiveCase({
                                caseNumber: `${activeCases.length + 1}`,
                                caseStatus: "Active",
                                caseDescription: "Newly created case.",
                                caseContext: "Generated by system",
                            })
                        }
                    >
                        Start Case
                    </Button>
                </CardContent>
            </Card>
        </div>
    );
}
